### ISSUE TITLE
JapaneseDateTypeHandlerTest inconsistent results

### ISSUE THREAD

**Issue by hazendaz** [mybatis/typehandlers-jsr310#26]
I'm unable to build this module on my local machine.  Possibly something with daylight savings time not sure.  

Build always works fine on travis-ci.

Here is what I get locally.  I'm in US Eastern time zone.

```
Failed tests:
  JapaneseDateTypeHandlerTest.shouldGetResultFromCallableStatement:76 expected:<Japanese Heisei 28-12-29> but was:<Japanese Heisei 28-12-28>
  JapaneseDateTypeHandlerTest.shouldGetResultFromResultSetByName:46 expected:<Japanese Heisei 28-12-29> but was:<Japanese Heisei 28-12-28>
  JapaneseDateTypeHandlerTest.shouldGetResultFromResultSetByPosition:61 expected:<Japanese Heisei 28-12-29> but was:<Japanese Heisei 28-12-28>
```

refs #12

**Comment by kazuki43zoo** [comment]
Hi @hazendaz , thanks for your report !

Oh.. I will fix at later.

**Comment by kazuki43zoo** [comment]
Hi @hazendaz , This issue occur on minus timezone (UTC - 1 〜 UTC - 12).
I've fixed via gh-27.

**Comment by hazendaz** [comment]
Thanks ill check it out today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
