### ISSUE TITLE
Support for threeten-extra

### ISSUE THREAD

**Issue by raupachz** [mybatis/typehandlers-jsr310#31]
[ThreeTen-Extra](https://github.com/ThreeTen/threeten-extra) is a small library that builds on the Java SE 8 java.time package. It provides some additional classes that come in handy as value types. 

We use it quite often in our projects and we already have several converters in place. Would be nice if we could add these type converters to mybatis/typehandlers-jsr310.

I don't think it would make sense to add a compile scope dependency to threeten-extra. Is there any other way to add type converters to this project? I do know some maven intrinsics but dependency scopes like optional and runtime I do not know much.

**Edit**
In my repo I added threeten-extra as an optional dependency.

```
<dependency>
  <groupId>org.threeten</groupId>
  <artifactId>threeten-extra</artifactId>
  <version>1.0</version>
  <scope>compile</scope>
  <optional>true</optional>
</dependency>
```

Now I can use typehandlers-jsr310 in my project even if threeten-extra is not included. Adding threeten-extra allows me to use the additional typehandlers. 

We just can't auto register the threeten-extra typehandlers in mybatis-3, since we don't know if threeten-extra is included or not.

**Comment by raupachz** [comment]
I opened #33 for this one.

**Comment by kazuki43zoo** [comment]
Close this issue because I've created mybatis/typehandlers-threeten-extra#1.
