### ISSUE TITLE
parameter 为null的情况下，Time.valueOf(parameter);会出问题。

### ISSUE THREAD

**Issue by cnhans** [mybatis/typehandlers-jsr310#5]
parameter 为null的情况下，Time.valueOf(parameter);会出问题。
其他地方的差不多。
example:
改成：
                if (parameter == null) {
            ps.setTime(i, null);
        } else {
            ps.setTime(i, Time.valueOf(parameter));
        }

**Comment by harawata** [comment]
Sorry, I couldn't understand.
I think you are talking about ```setNonNullParameter``` method.
As the name implies, the method is called only when the parameter is not null.

If you are experiencing a problem, please let us know how to reproduce the problem first.

**Comment by harawata** [comment]
No reply.
